'use strict';
const assert=require('node:assert/strict');
const E=require('./traditional-engine.js');
const B=require('./biwheel-core.js');
const birth=2451545;
const calc=(jd,id)=>({name:['Sol','Lua'][id]||'P'+id,lon:E.mod(100+id*30+(jd-birth)*(id+1)),speed:id+1,lat:0});
const natal=B.snapshot(birth,calc,[0,1]);
assert.deepEqual(natal.map(x=>x.lon),[100,130]);
const transit=B.transit(birth+10,calc,[0,1]);
assert.deepEqual(transit.positions.map(x=>x.lon),[110,150]);
const target=birth+E.TROPICAL_YEAR*10.5;
const prog=B.secondaryProgression(birth,target,calc,[0,1]);
assert.ok(Math.abs(prog.age-10.5)<1e-9);
assert.ok(Math.abs(prog.jd-(birth+10.5))<1e-9);
const trueArc=B.solarArc(birth,target,natal,jd=>calc(jd,0).lon,{mode:'true'});
assert.ok(Math.abs(trueArc.arc-10.5)<1e-9);
assert.deepEqual(trueArc.positions.map(x=>x.lon),[110.5,140.5]);
const mean=B.solarArc(birth,target,natal,jd=>calc(jd,0).lon,{mode:'mean'});
assert.ok(Math.abs(mean.arc-10.5*.98564736)<1e-9);
const compare=B.compareSolarArc(birth,target,natal,jd=>calc(jd,0).lon);
assert.ok(Number.isFinite(compare.difference));
assert.throws(()=>B.solarArc(birth,target,natal,jd=>0,{mode:'invented'}),/Modo/);
assert.throws(()=>B.snapshot(birth,()=>({lon:NaN}),[0]),/Posição ausente/);
console.log('Biwheel tests: OK (transit, fractional progression, true/mean solar arc)');
