(function(root,factory){
  const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.OAPortableBackup=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';const SCHEMA='oa-portable-backup/v1',PREFIXES=['oa-','obs-','astro-'];
  function collect(storage){const records={};for(let i=0;i<storage.length;i++){const key=storage.key(i);if(PREFIXES.some(prefix=>key.startsWith(prefix)))records[key]=storage.getItem(key)}return records}
  function create(storage,metadata={}){return {schema:SCHEMA,createdAt:new Date().toISOString(),scope:'local-device-explicit-export',records:collect(storage),metadata:{appVersion:metadata.appVersion||'unknown',containsPersonalData:true}}}
  function validate(bundle){if(!bundle||bundle.schema!==SCHEMA||!bundle.records||typeof bundle.records!=='object'||Array.isArray(bundle.records))throw Error('Backup incompatível.');for(const [key,value] of Object.entries(bundle.records))if(!PREFIXES.some(prefix=>key.startsWith(prefix))||typeof value!=='string')throw Error('Registro não permitido: '+key);return true}
  function restore(storage,bundle,{replace=false}={}){validate(bundle);const previous={};try{for(const [key,value] of Object.entries(bundle.records)){previous[key]=storage.getItem(key);if(!replace&&previous[key]!==null)throw Error('Conflito de restauração: '+key);storage.setItem(key,value)}}catch(error){for(const [key,value] of Object.entries(previous))value===null?storage.removeItem(key):storage.setItem(key,value);throw error}return {restored:Object.keys(bundle.records).length}}
  function erase(storage){const keys=[];for(let i=0;i<storage.length;i++){const key=storage.key(i);if(PREFIXES.some(prefix=>key.startsWith(prefix)))keys.push(key)}keys.forEach(key=>storage.removeItem(key));return {erased:keys.length}}
  const request=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
  const transactionDone=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Transação abortada.'))});
  async function collectIndexedDB(factory=globalThis.indexedDB){
    if(!factory)return[];const databases=typeof factory.databases==='function'?await factory.databases():[],out=[];
    for(const info of databases.filter(x=>x.name&&PREFIXES.some(prefix=>x.name.startsWith(prefix)))){
      try{const db=await request(factory.open(info.name)),stores=[];for(const name of db.objectStoreNames){const tx=db.transaction(name,'readonly'),store=tx.objectStore(name),keys=await request(store.getAllKeys()),values=await request(store.getAll());stores.push({name,keyPath:store.keyPath,autoIncrement:store.autoIncrement,records:values.map((value,index)=>({key:keys[index],value}))});await transactionDone(tx)}out.push({name:db.name,version:db.version,stores});db.close()}catch(error){out.push({name:info.name,error:error.message})}
    }return out;
  }
  async function createComplete(storage,metadata={},factory=globalThis.indexedDB){const bundle=create(storage,metadata);bundle.indexedDB=await collectIndexedDB(factory);bundle.schema='oa-portable-backup/v2';return bundle}
  function validateComplete(bundle){if(bundle?.schema==='oa-portable-backup/v1')return validate(bundle);if(bundle?.schema!=='oa-portable-backup/v2'||!Array.isArray(bundle.indexedDB))throw Error('Backup completo incompatível.');validate({...bundle,schema:SCHEMA});for(const db of bundle.indexedDB)if(typeof db.name!=='string'||!Array.isArray(db.stores))throw Error('Banco IndexedDB inválido.');return true}
  async function restoreComplete(storage,bundle,{replace=false,factory=globalThis.indexedDB}={}){validateComplete(bundle);const local=restore(storage,{...bundle,schema:SCHEMA},{replace});let indexed=0;try{for(const saved of bundle.indexedDB){if(saved.error)continue;const db=await request(factory.open(saved.name));for(const savedStore of saved.stores){if(!db.objectStoreNames.contains(savedStore.name))throw Error('Store ausente: '+saved.name+'/'+savedStore.name);const tx=db.transaction(savedStore.name,'readwrite'),store=tx.objectStore(savedStore.name);if(replace)store.clear();for(const record of savedStore.records)store.keyPath==null?store.put(record.value,record.key):store.put(record.value);await transactionDone(tx);indexed+=savedStore.records.length}db.close()}return {restored:local.restored,indexedDBRecords:indexed}}catch(error){throw Error('Dados locais restaurados, mas IndexedDB falhou: '+error.message)} }
  async function eraseComplete(storage,factory=globalThis.indexedDB){const local=erase(storage),databases=typeof factory?.databases==='function'?await factory.databases():[];let indexedDB=0;for(const info of databases)if(info.name&&PREFIXES.some(prefix=>info.name.startsWith(prefix))){await request(factory.deleteDatabase(info.name));indexedDB++}return {erased:local.erased,indexedDBDatabases:indexedDB}}
  return {SCHEMA,PREFIXES,collect,create,validate,restore,erase,collectIndexedDB,createComplete,validateComplete,restoreComplete,eraseComplete};
});
